<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>BiliNative.Updater</RootNamespace>
    <AssemblyName>NovaClip.Updater</AssemblyName>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
</Project>
