<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>NovaClip.Infrastructure</RootNamespace>
    <AssemblyName>NovaClip.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NovaClip.Contracts\NovaClip.Contracts.csproj" />
    <ProjectReference Include="..\NovaClip.Core\NovaClip.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
